name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          output_filepath: github-metrics.svg
