name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: mynamemyway
